name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Download ImGui
        run: setup_imgui.bat
        shell: cmd

      - name: Build DLL
        run: build_enemy_counter.bat
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arcdps_enemy_counter_dll
          path: out/arcdps_enemy_counter.dll
